### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by ari-party** [SpaceGameDev568/FG_DiscordRP#1]
### Operating System

Winblows 10/11

### Environment

Client (You are connecting to a dedicated server)

### Game Version

Early Access

### SML Version

v3.7.0

### Mod Version

v1.2.10

### Describe the bug

Custom presence does not appear, default one does.
![image](https://github.com/SpaceGameDev568/FG_DiscordRP/assets/49074962/1f5b7df2-f53c-4732-804d-257e618d3483)
(In server during screenshot)

### Expected Behavior

For the presence to correctly appear.

### Contact agreement

- [X] I agree to allow the developer to contact me for more information regarding this bug if necessary.

**Comment by SpaceGameDev568** [comment]
Hi, thanks for reporting this issue! Could you please provide your SMM debug info so that I can investigate?<br>
<img width="341" alt="Generate Debug" src="https://github.com/SpaceGameDev568/FG_DiscordRP/assets/95051062/e3ab0d12-97ad-4d8c-b58d-91ea37e8a8c5"><br>
I'd also like to know if you're able to see anything in the main menu or during a single-player session on your Discord profile.

**Comment by ari-party** [comment]
[SMMDebug_2024-4-5_10-45-48.zip](https://github.com/SpaceGameDev568/FG_DiscordRP/files/14883848/SMMDebug_2024-4-5_10-45-48.zip)

**Comment by SpaceGameDev568** [comment]
Alright, I think I've been able to replicate your issue by having Discord closed when starting the game. Did you start Discord after you opened the game?

**Comment by ari-party** [comment]
Discord had been open the entire time.

**Comment by SpaceGameDev568** [comment]
Hey, I'm finding it very difficult to reproduce this issue. Currently, I have two ideas that you can test on your own to give me some more information to work with.

Firstly, you can try reverting your mod version to v1.2.2 of DRP. Since it uses a different backend system for handling rich presence, it may resolve the issue.

Secondly, (if you haven't already) go ahead and try some other applications that have rich presence and see if they work. If other apps don't work with rich presence either, it may be an issue with the Discord client configuration rather than my specific application.

Please let me know how both of those go, and thank you for your patience!

**Comment by ari-party** [comment]
No problems with my Discord client, it works just fine with many different games.

Will try downgrading to 1.2.2

**Comment by ari-party** [comment]
I have downgraded to 1.2.2 and it is still not functional.

Here is a [video demonstration](https://astrid.email/u/FactoryGame-Win64-Shipping_6o1Lw27EG7.mp4). Since it's 1080p and the file was too large, I uploaded it with [Zipline](https://github.com/diced/zipline).

**Comment by SpaceGameDev568** [comment]
Thanks for the extra information. I'm trying various things to see if I can determine what's wrong here, and in the process, I found a [potential issue](https://github.com/ryanjon2040/Discord-UE4/issues/21) with the wrapper I'm using for the Discord SDK. I have updated the mod to roll back the SDK to an older, but more stable version. Please make sure you update both the client and the server to v1.2.11, and let me know how that goes. Cheers!

**Comment by ari-party** [comment]
> Thanks for the extra information. I'm trying various things to see if I can determine what's wrong here, and in the process, I found a [potential issue](https://github.com/ryanjon2040/Discord-UE4/issues/21) with the wrapper I'm using for the Discord SDK. I have updated the mod to roll back the SDK to an older, but more stable version. Please make sure you update both the client and the server to v1.2.11, and let me know how that goes. Cheers!

You have to install the mod on the dedicated server as well? (Currently it is not.)

**Comment by SpaceGameDev568** [comment]
Yes, in order for the mod to work properly client-side, it must be installed on the server, too.

**Comment by ari-party** [comment]
Hey, apologies. I just saw that I had a Discord modification which disables the RPC server. Sorry for wasting your time!

**Comment by SpaceGameDev568** [comment]
I'm laughing my ass off! Don't worry about wasting my time, I'm just glad the problem is resolved. Have a good one!
